export const forceFetchJobs = false

export const jobSectors = [
    "Any",
    "Academic",
    "Accounting",
    "Admin",
    "Advertising",
    "Agriculture",
    "Automotive",
    "Aviation",
    "Banking",
    "Business Management",
    "Call Centre",
    "Chemical",
    "Clothing",
    "Construction",
    "Consulting",
    "Cruise Ship",
    "Defence",
    "Design Services",
    "E-Commerce",
    "Education",
    "Engineering",
    "Entertainment",
    "Environmental",
    "Fashion",
    "Finance",
    "FMCG",
    "Freight",
    "General",
    "Government & Parastatals",
    "Graduate",
    "Health & Safety",
    "Health Fitness & Beauty",
    "Hospitality",
    "Human Resources",
    "Import & Export",
    "Insurance",
    "Internet",
    "Investment",
    "IT",
    "Legal",
    "Lifestyle",
    "Logistics",
    "Management",
    "Manufacturing",
    "Market Research",
    "Marketing",
    "Media",
    "Medical",
    "Mining",
    "Motoring",
    "NGO & Non-profit",
    "Petrochemical",
    "Pharmaceutical",
    "PR & Communication",
    "Procurement",
    "Property",
    "Purchasing",
    "Real Estate",
    "Recruitment",
    "Research",
    "Retail",
    "Sales",
    "Security",
    "Social Services",
    "Soft Skills",
    "Sports",
    "Stockbroking",
    "Technical",
    "Technology",
    "Telecommunications",
    "Trades & Services",
    "Travel & Tourism",
    "Warehousing"
]