// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function ExecCmd(arg1) {
  return window['go']['main']['App']['ExecCmd'](arg1);
}

export function GenKeystore(arg1) {
  return window['go']['main']['App']['GenKeystore'](arg1);
}

export function GetPort() {
  return window['go']['main']['App']['GetPort']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectSaveDir() {
  return window['go']['main']['App']['SelectSaveDir']();
}
