// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseApp():Promise<void>;

export function ExecCmd(arg1:string):Promise<any>;

export function GenKeystore(arg1:string):Promise<any>;

export function GetPort():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function SelectSaveDir():Promise<any>;
