// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function GetPort() {
  return window['go']['main']['App']['GetPort']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
