import type { Metadata } from "next";
import "@repo/ui/styles/all.scss"
import Layout from "@/components/Layout";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

   
  return (
    
       <html lang="en" className="dark" data-theme="tb">
      <body
      
      >
        <Layout>{children}</Layout>
      </body>
    </html> 
  );
}
