// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseApp():Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function GenThumbnails(arg1:string):Promise<Array<main.VidThumb>>;

export function GetArgs():Promise<Array<string>>;

export function GetPort():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function ImportVideo():Promise<string>;
