// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseApp():Promise<void>;

export function GenThumbnails(arg1:string):Promise<Array<main.VidThumb>>;

export function GetPort():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function ImportVideo():Promise<string>;
